### ISSUE TITLE
Add basic I18n english translations

### ISSUE THREAD

**Issue by gil27** [flexait/acl_manager#5]
We need to add I18n to basic crud operations of gem

![captura de tela 2017-10-13 as 17 34 04](https://user-images.githubusercontent.com/1313442/31565323-bdfc2018-b03c-11e7-9f6a-9ba2849b9e7f.png)

**Comment by massa1240** [comment]
i am going to work on that :)

**Comment by gil27** [comment]
Awesome @massa1240, thank you very much
