### ISSUE TITLE
Allow users to create roles via rake task

### ISSUE THREAD

**Issue by gil27** [flexait/acl_manager#6]
During gem setup we need to pass through the following step:

```
AclManager::Role.create(name: 'admin', active: true, description: 'gives users     admin access')
role = AclManager::Role.first
role.acls << AclManager::Acl.first
user = User.first
user.roles << role
```
It would be nice to have a rake task where we pass something like this: `rake acl_manager g role name:admin, active:true, description:'foo bar'`

**Comment by rakesh-verma-16** [comment]
I'd like to work on this one. :) Can I claim it?

**Comment by gil27** [comment]
Yes, for sure @rakesh-verma-16. Your help are welcomed :)

**Comment by RORingBBK** [comment]
Submitted in PR #13
